services:
  - type: web
    name: spam-detector-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: >
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn --bind 0.0.0.0:$PORT spam_detector.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: spam-detector-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,new-one-5q6r.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: spam_detector.settings
      - key: PYTHONPATH
        value: .
      - key: PORT
        value: 8000
      - key: CORS_ALLOWED_ORIGINS
        value: "https://new-one-5q6r.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://new-one-5q6r.onrender.com"

databases:
  - name: spam-detector-db
    databaseName: spam_detector
    user: spam_detector
    plan: free 